Dodanie dwóch endpointów do wypożyczania rowerów
io2-2021-wed-brodka/L_Combine pull request #32
Opened 2021-04-03 22:49 UTC by smogork

Dodanie endpointów:
/api/bikes/rented GET
/api/bikes/rented POST

2021-04-04 15:53 UTC, wesolowskip requested changes
Postman wskazuje na to, że ogólnie działa

2021-04-04 15:53 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/BikesController.cs
> +                .Select(r => BikeDTOFactory.CreateBikeDTO(r.Bike, r.User)).ToArray();
.ToList() jest szybsze niż .ToArray() przy tego typu rzeczach z tego co kiedyś czytałem, zresztą ja bym najlepiej zostawił tego Selecta i po nim już nic nie zmieniał. Wtedy rentedBikes będzie miało typ IEnumerable, ale na spokojnie można zwrócić taki typ (json to i tak przerobi sobie na tablicę)

2021-04-04 15:53 UTC, wesolowskip commented on Backend/BackendAPI/Repository/Repositories/RentalRepository.cs
> +        public IEnumerable<Rental> FindActiveRentals(int userId)
może zróbmy tutaj podobnie jak w innych tego typu metodach, czyli zwróćmy IList a nie IEnumerable

2021-04-04 15:53 UTC, wesolowskip commented on Backend/BackendAPI/Repository/Repositories/RentalRepository.cs
> +            return dbContext.Rentals
wydaje mi się, że tutaj można zgodnie z pozostałymi metodami użyć GetAllRentals (oczywiście to drobnostka, więc jak ci się nie chce poprawiać to niech zostanie)

2021-04-04 15:53 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/BikesController.cs
> +            Bike bike = bikeRepository.GetByID(bikeId);
Może jak bike jest nullem to wstawmy tu `return new NotFoundObjectResult(new ErrorDTO("Bike not found"));` . Wiem że w specyfikacji nie ma czegoś takiego, więc tutaj jak będziesz uważał

2021-04-04 15:53 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/BikesController.cs
> +                || bike.BikeStation?.State != ClassLibrary.BikeStationState.Working)
Sprytnie, bo działa to też faktycznie gdy rower jest wypożyczony przez kogo innego. Szacuneczek :)

2021-04-04 15:53 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/BikesController.cs
> +            return Ok(BikeDTOFactory.CreateBikeDTO(bike, userRepository.GetByID(GetRequestingUserID)));
zły status, powinno być 201 czyli `CreatedResult`

2021-04-04 15:53 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/BikesController.cs
> +
Może dopiszmy tu wielkimi literami kometnarz na przyszłość żeby pamiętac, by w przyszłości dodać też dodatkowego ifa 
![obraz](https://user-images.githubusercontent.com/69988486/113514137-3b12e500-956d-11eb-9ddd-848b5f772bff.png)

2021-04-04 15:53 UTC, wesolowskip commented on Libraries/ClassLibrary/DTO/RentBikeDTO.cs
> +﻿using System;
Ten plik na pewno jest potrzebny? mamy IdDTO

2021-04-04 15:53 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/BikesController.cs
> +        public ActionResult<BikeDTO> RentedPost([FromBody] RentBikeDTO rent)
zmienić na IdDTO, specjalnie napisałem IdDTO by właśnie do każdego obiektu nie pisać osobno klasy zawierającej tylko i wyłacznie id

2021-04-04 15:53 UTC, wesolowskip commented on Backend/BackendAPI/Repository/Interfaces/IRentalRepository.cs
> +        IEnumerable<Rental> FindActiveRentals(int userId);
tutaj zrobić zwracany IList

2021-04-05 09:39 UTC, smogork commented on Libraries/ClassLibrary/DTO/RentBikeDTO.cs
> +﻿using System;
Nieiedzialem jeszcze ze dziala zwracanie obiektow anonimowych

2021-04-06 09:07 UTC, wesolowskip requested changes

2021-04-06 09:07 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/BikesController.cs
> +                throw new HttpResponseException("Wrong Bike Id", 404);
Ja wiem że tego nie ma w specce ale jak już to dopiszą to pewnie będzie niezgodnie. To zwraca jsona o polu "Error" a według ramla wszędzie gdzie piszą o 404 chcemy jsona o polu "messsage" (typ ErrorDTO). Ja ogólnie pomijałem TryParse i robiłem po prostu robiłem Parse, więc jeśli wolisz TryParse to daj znać to ja sie dostosuję i pozmieniam (może faktycznie TryParse jest lepsze). W każdym razie tutaj po prostu bardziej przyszłościowo lepiej zwrócić NotFoundObjectResult(new ErrorDTO(){Message = "Bike not found"}) (zakładam, że kiedyś dopiszą w specyfikacji tutaj 404)

2021-04-06 09:07 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/BikesController.cs
> +                throw new HttpResponseException("Wrong Bike Id", 404);
to samo co wyżej

2021-04-06 09:07 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/BikesController.cs
> +            return new CreatedResult("/api/bikes/rented", BikeDTOFactory.CreateBikeDTO(bike, userRepository.GetByID(GetRequestingUserID)));
Tutaj w sumie mam wątpliowści co do lokacji. Nigdy nie miałem do czynienia z czymś takim i ja osobiscie zwracałem tu id obiektu. Musimy uspójnić konweencję. Wg tego co czytam w 201 powinien iść URI którym można sie dostać do tego konkretnego obiektu, to nie wiem jak to intepretujesz

2021-04-06 09:12 UTC, wesolowskip approved these changes
Pewne rzeczy do przegadania na później (HttpResponseException ma pole Errror a nie message oraz lokacja w responsie 201)

2021-04-06 09:13 UTC, merged