Połączenie bike-service z backendem
io2-2021-wed-brodka/L_Combine pull request #38
Opened 2021-04-07 14:54 UTC by KacperWalasek

Lista pokazuje tylko id roweru, bo według nowej dokumentacji get na bikes/rented nie zwraca daty wypożyczenia

2021-04-07 15:56 UTC, widomskip requested changes

2021-04-07 15:56 UTC, widomskip commented on Frontend/UserTech/src/app/components/list-rented-bikes/list-rented-bikes.component.ts
> +  reservedBikes: Bike[] = [];
to się chyba powinno nazywać rentedBikes

2021-04-07 15:56 UTC, widomskip commented on Frontend/UserTech/src/app/services/bike.service.ts
> +    return this.http.get<BikesDTO>(`${this.baseUrl}/rented`);
Czy chcemy jawnie sprawdzać czy użytkownik jest zalogowany? Bo samo wywołanie tej metody dla niezalogowanego użytkownika jest czymś błędnym. A jeżeli już pójdzie taki request to incetreptor przechwytuje i reroutuje dla 401.

2021-04-07 19:02 UTC, KacperWalasek commented
Nie merguj tego pr po zaprovowaniu, bo mogą być konflikty z rp o zwracaniu rowerów. Lepiej zmergujmy najpierw tamto, a potem ja zmerguje ten rozwiązując konflikty

2021-04-08 16:07 UTC, widomskip approved these changes

2021-04-09 09:41 UTC, widomskip approved these changes

2021-04-09 09:41 UTC, merged