Bike return view
io2-2021-wed-brodka/L_Combine pull request #39
Opened 2021-04-07 17:16 UTC by widomskip

2021-04-07 18:57 UTC, KacperWalasek requested changes

2021-04-07 18:57 UTC, KacperWalasek commented on Frontend/UserTech/src/app/app-routing.module.ts
> -        canActivate: [StationActiveGuard]
Dlaczego ten guard nie jest potrzebny?

2021-04-07 18:57 UTC, KacperWalasek commented on Frontend/UserTech/src/app/components/return-bike/return-bike.component.html
> +  </div>
Nie powinno się dać wybrać stacji zablokowanej (nie reagować na kliknięcie albo nie pokazywać takiej stacji w liście)

2021-04-07 18:57 UTC, KacperWalasek commented on Frontend/UserTech/src/app/services/rent-bike.service.ts
> +  return(bikeId: number, stationId: number): Observable<any> {
Nie jestem przekonany czy return to dobra nazwa na funkcję. Zmieniłbym jednak na coś co nie jest słowem kluczowym js'a.

2021-04-08 16:20 UTC, widomskip commented on Frontend/UserTech/src/app/app-routing.module.ts
> -        canActivate: [StationActiveGuard]
Podstawowy endpoint stacji zwraca 404 dla stacji, które są nieaktywne, a w tym module nie będziemy nawet pobierać stacji, które są nieaktywne.

2021-04-08 16:27 UTC, widomskip commented on Frontend/UserTech/src/app/components/return-bike/return-bike.component.html
> +  </div>
Nie wyświetli się taka stacja, bo endpoint jej nie zwróci. Usunę logikę stanu stacji, bo w tym widoku będziemy zawsze listować tylko aktywne stacje.

2021-04-08 21:18 UTC, KacperWalasek approved these changes

2021-04-08 21:18 UTC, merged