Dodanie logiki rezerwacji rowerów
io2-2021-wed-brodka/L_Combine pull request #55
Opened 2021-04-19 23:31 UTC by smogork

Stworzono repozytorium oraz tabele na rezerwacje.
Stworzono endpointy /api/bikes/reserved*.

Sprawdzenia czy dane sa prawidlowe robi sie tak paskudnie dluga, ze nalezy zaimplementowac ChainOfResponsibility w endpointach wg mnie.

2021-04-20 11:57 UTC, wesolowskip requested changes

2021-04-20 11:57 UTC, wesolowskip commented on Backend/BackendAPI/Repository/Interfaces/IReservationRepository.cs
> +        IList<Reservation> GetActiveReservationsByUser(User user);
te metody poprawić na przyjmujące idki a nie encje

2021-04-20 11:57 UTC, wesolowskip commented on Libraries/ClassLibrary/DTO/ReservationDTO.cs
> +    public class ReservationDTO
wg specki może zmienić nazwę na ReservedBikeDTO

2021-04-20 11:57 UTC, wesolowskip commented on Libraries/ClassLibrary/DTO/ReservationDTO.cs
> +        public string BikeID { get; set; }
zminieć na BikeId bo boję się że json może coś nie ogarnać

2021-04-20 11:57 UTC, wesolowskip commented on Backend/BackendAPI/Repository/Repositories/ReservationRepository.cs
> +            return dbContext.Reservations.Where(r => r.ExpireDate.CompareTo(DateTime.Now) > 0);
dodać include Bike then include BikeStation - będzie przydatne do zwracania dto

2021-04-20 11:57 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/ReservationController.cs
> +        }
nie zwracamy tu DTO tylko nasze obiekty bazowe!

2021-04-21 11:21 UTC, wesolowskip submitted a review, later dismissed

2021-04-21 11:56 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/ReservedBikesController.cs
> +                throw new HttpResponseException("Bike already rented", 422);*/
Zobaccz, że jesli w tym sprawdzeniu wyjdzie ci że jest wypożczyony (!= null) to równie dobrze w tym niżej dostaniesz FindActiveReservation=null czyli dostaniesz w tym niżej błąd

2021-04-21 11:58 UTC, wesolowskip commented on Backend/BackendAPI/Controllers/ReservedBikesController.cs
> +                throw new HttpResponseException("Bike already rented", 422);*/
Czyli sprawdzenie czy jest wypożyczony jest nadmiarowe

2021-04-21 12:02 UTC, smogork commented on Backend/BackendAPI/Controllers/ReservedBikesController.cs
> +                throw new HttpResponseException("Bike already rented", 422);*/
Masz rację, to wystarczy.

2021-04-21 12:06 UTC, wesolowskip submitted a review, later dismissed

2021-04-21 12:09 UTC, wesolowskip approved these changes

2021-04-21 12:10 UTC, merged