Feature/test frontend
io2-2021-wed-brodka/L_Combine pull request #57
Opened 2021-04-20 19:25 UTC by KacperWalasek

2021-04-20 19:27 UTC, KacperWalasek commented
Przegapiłem testy do app-component. Za chwilę wrzucę poprawkę

2021-04-20 20:00 UTC, widomskip requested changes

2021-04-20 20:00 UTC, widomskip commented on Frontend/UserTech/src/app/components/list-rented-bikes/list-rented-bikes.component.spec.ts
> +  });
zdublowany test

2021-04-20 20:00 UTC, widomskip commented on Frontend/UserTech/src/app/dto/bike-dto.ts
> +  user: UserDTO | null;
powinno się raczej pisać station? i user? imo

2021-04-21 09:23 UTC, widomskip approved these changes

2021-04-21 09:23 UTC, merged