Zarządzanie specjalistami
io2-2021-wed-brodka/L_Combine pull request #82
Opened 2021-05-14 15:22 UTC by KacperWalasek

2021-05-14 17:00 UTC, widomskip requested changes

2021-05-14 17:01 UTC, widomskip commented
Nie mogę dodać użytkownika 'tech' mimo iż takiego nie ma na liście.

2021-05-14 19:13 UTC, KacperWalasek commented on Frontend/Admin/src/app/components/block-user/block-user.component.spec.ts
> +  it('#blockUser should call service function              ', ()=>{
Nie wiem jak to się stało xD

2021-05-14 19:16 UTC, KacperWalasek commented
> Nie mogę dodać użytkownika 'tech' mimo iż takiego nie ma na liście.

To dziwne, bo u mnie wszystko działa. Dla innych loginów wszystko działa? Jaki jest komunikat?

2021-05-15 11:27 UTC, widomskip commented
> > Nie mogę dodać użytkownika 'tech' mimo iż takiego nie ma na liście.
> 
> To dziwne, bo u mnie wszystko działa. Dla innych loginów wszystko działa? Jaki jest komunikat? (Zamknąłem pr przez przypadek jbc)

Po postawieniu bazy od nowa działa, pewnie były jakieś śmieci

2021-05-15 14:28 UTC, widomskip approved these changes
git

2021-05-15 14:28 UTC, merged